Added boolean check for inserted argument at prompt
js-tasks-ru/jsbasic-20200903_albezver pull request #3
Opened 2020-09-14 10:37 UTC by kron2011

2020-09-14 10:44 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-09-15 08:25 UTC, koalex requested changes
Исправь замечания

2020-09-15 08:25 UTC, koalex commented on 1-module/2-task/index.js
> +sayHello();
удали строку 33

2020-09-15 08:25 UTC, koalex commented on 1-module/2-task/index.js
> -  // ваш код...
Неправильно. В задании указано что должна быть проверка на мин. длину имени в 4 символа и наличие пробела.
Например вот так:)
```
function isValid(name) {
  if (!name || name.indexOf(' ') !== -1 || name.length < 4) {
    return false;
  }

  return true;
}
```

2020-09-15 09:36 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Допишите функцию валидации имени пользователя
+ если содержит пробелы, то false
+ если имя корректное, то true
+ если меньше 4 символов то false
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-09-15 09:38 UTC, koalex approved these changes
вроде ОК

2020-09-15 09:38 UTC, merged